version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  audio-recorder:
    image: iqtlabs/edgetech-audio-recorder:latest
    build:
      context: ./audio-recorder
      dockerfile: ./Dockerfile
    devices:
      - "/dev/snd:/dev/snd"
    restart: unless-stopped
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    depends_on: 
      - mqtt
    env_file:
      - path: ./audio-recorder.env
        required: false
