version: "3"
services:
  audio-recorder:
    image: iqtlabs/edgetech-audio-recorder:${SERVICES_IMAGE_TAG:-stable}
    restart: always
    network_mode: "none"
    environment:
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - "./data:/flash/telemetry/hydrophone"
    devices:
      - "/dev/snd:/dev/snd"
